# Frontend for MLFLow

In [37]:
import mlflow
from mlflow import MlflowClient
import polars as pl
import os
from pathlib import Path

---

In [2]:
TRACKING_URI = "http://localhost:5051"
mlflow.set_tracking_uri(TRACKING_URI)
client = MlflowClient(TRACKING_URI)

In [3]:
client.search_experiments()

[<Experiment: artifact_location='file:///workspace/mlruns/hyper-sweep-v1', creation_time=1788570031513, experiment_id='352020498793752715', last_update_time=1788570031513, lifecycle_stage='active', name='hyper-sweep-v1', tags={}, workspace='default'>,
 <Experiment: artifact_location='file:///workspace/mlruns/canary-selection-v1', creation_time=1788570010128, experiment_id='311537756843906090', last_update_time=1788570010128, lifecycle_stage='active', name='canary-selection-v1', tags={}, workspace='default'>,
 <Experiment: artifact_location='file:///workspace/mlruns/reproduction-nc-grokking-v1', creation_time=1788569988187, experiment_id='836777792413634741', last_update_time=1788569988187, lifecycle_stage='active', name='reproduction-nc-grokking-v1', tags={}, workspace='default'>,
 <Experiment: artifact_location='mlflow-artifacts:/0', creation_time=1788569815669, experiment_id='0', last_update_time=1788569815669, lifecycle_stage='active', name='Default', tags={}, workspace='default'>]

In [ ]:
client.search_runs("836777792413634741")

---

# Fixing Runs

List runs:
```bash
sbatch list_runs.sbatch reproduction-nc-grokking-v1 -o /workspace/cache/reproduction-nc-grokking-v1_runs.parquet
sbatch list_runs.sbatch canary-selection-v1 -o /workspace/cache/canary-selection-v1_runs.parquet
sbatch list_runs.sbatch hyper-sweep-v1 -o /workspace/cache/hyper-sweep-v1_runs.parquet
```

Download:
```bash
scp ronholzapfel@login.ai-lab.uni-luebeck.de:~/privacy-and-grokking/cache/reproduction-nc-grokking-v1_runs.parquet cache/reproduction-nc-grokking-v1_runs.parquet
scp ronholzapfel@login.ai-lab.uni-luebeck.de:~/privacy-and-grokking/cache/canary-selection-v1_runs.parquet cache/canary-selection-v1_runs.parquet
scp ronholzapfel@login.ai-lab.uni-luebeck.de:~/privacy-and-grokking/cache/hyper-sweep-v1_runs.parquet cache/hyper-sweep-v1_runs.parquet
```

In [85]:
BASE_PATH = Path.cwd().parent
COMMANDS_FOLDER = BASE_PATH / "commands"
CACHE_PATH = BASE_PATH / "cache"
SCRIPTS_PATH = BASE_PATH / "scripts"
# FILE_PATH = CACHE_PATH / "reproduction-nc-grokking-v1_runs.parquet"
# FILE_PATH = CACHE_PATH / "canary-selection-v1_runs.parquet"
FILE_PATH = CACHE_PATH / "hyper-sweep-v1_runs.parquet"

In [86]:
df = pl.read_parquet(FILE_PATH)
df.describe()

shape: (9, 176)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ run_id    ┆ experimen ┆ status   ┆ … ┆ data.mask ┆ duration_ ┆ duration_ ┆ __index_l │
│ ---       ┆ ---       ┆ t_id      ┆ ---      ┆   ┆ .model_in ┆ seconds   ┆ formatted ┆ evel_0__  │
│ str       ┆ str       ┆ ---       ┆ str      ┆   ┆ dex       ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆          ┆   ┆ ---       ┆ f64       ┆ str       ┆ f64       │
│           ┆           ┆           ┆          ┆   ┆ f64       ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 798       ┆ 798       ┆ 798      ┆ … ┆ 798.0     ┆ 798.0     ┆ 798       ┆ 798.0     │
│ null_coun ┆ 0         ┆ 0         ┆ 0        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0.0       │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null      ┆ null     ┆ … ┆ 2.700501  ┆ 16509.960 ┆ null      ┆ 398.5     │
│           ┆           ┆           ┆          ┆   ┆           ┆ 557       ┆           ┆           │
│ std       ┆ null      ┆ null      ┆ null     ┆ … ┆ 1.737988  ┆ 7042.2383 ┆ null      ┆ 230.50705 │
│           ┆           ┆           ┆          ┆   ┆           ┆ 84        ┆           ┆           │
│ min       ┆ 00508d577 ┆ 352020498 ┆ FINISHED ┆ … ┆ 0.0       ┆ 1541.8378 ┆ 1h 00m    ┆ 0.0       │
│           ┆ f10474695 ┆ 793752715 ┆          ┆   ┆           ┆ 54        ┆ 20s       ┆           │
│           ┆ 884351934 ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 1d4…      ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 25%       ┆ null      ┆ null      ┆ null     ┆ … ┆ 1.0       ┆ 13482.455 ┆ null      ┆ 199.0     │
│ 50%       ┆ null      ┆ null      ┆ null     ┆ … ┆ 3.0       ┆ 17866.265 ┆ null      ┆ 399.0     │
│ 75%       ┆ null      ┆ null      ┆ null     ┆ … ┆ 4.0       ┆ 19001.448 ┆ null      ┆ 598.0     │
│ max       ┆ ffdd11bc2 ┆ 352020498 ┆ RUNNING  ┆ … ┆ 5.0       ┆ 29403.837 ┆ 8h 10m    ┆ 797.0     │
│           ┆ f6a4b5585 ┆ 793752715 ┆          ┆   ┆           ┆           ┆ 03s       ┆           │
│           ┆ 481a29c8d ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ f59…      ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [87]:
keep_df = df.filter((pl.col("status") != "RUNNING") & pl.col("run_name").str.contains("MADD_MSE").not_())
remove_df = df.filter((pl.col("status") == "RUNNING") | pl.col("run_name").str.contains("MADD_MSE"))

In [88]:
keep_df.describe()

shape: (9, 176)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ run_id    ┆ experimen ┆ status   ┆ … ┆ data.mask ┆ duration_ ┆ duration_ ┆ __index_l │
│ ---       ┆ ---       ┆ t_id      ┆ ---      ┆   ┆ .model_in ┆ seconds   ┆ formatted ┆ evel_0__  │
│ str       ┆ str       ┆ ---       ┆ str      ┆   ┆ dex       ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆          ┆   ┆ ---       ┆ f64       ┆ str       ┆ f64       │
│           ┆           ┆           ┆          ┆   ┆ f64       ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 678       ┆ 678       ┆ 678      ┆ … ┆ 678.0     ┆ 678.0     ┆ 678       ┆ 678.0     │
│ null_coun ┆ 0         ┆ 0         ┆ 0        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0.0       │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null      ┆ null     ┆ … ┆ 2.735988  ┆ 18697.909 ┆ null      ┆ 458.35988 │
│           ┆           ┆           ┆          ┆   ┆           ┆ 549       ┆           ┆ 2         │
│ std       ┆ null      ┆ null      ┆ null     ┆ … ┆ 1.740873  ┆ 4948.8354 ┆ null      ┆ 196.09214 │
│           ┆           ┆           ┆          ┆   ┆           ┆ 05        ┆           ┆ 7         │
│ min       ┆ 00508d577 ┆ 352020498 ┆ FINISHED ┆ … ┆ 0.0       ┆ 12846.735 ┆ 3h 34m    ┆ 118.0     │
│           ┆ f10474695 ┆ 793752715 ┆          ┆   ┆           ┆           ┆ 06s       ┆           │
│           ┆ 884351934 ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 1d4…      ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 25%       ┆ null      ┆ null      ┆ null     ┆ … ┆ 1.0       ┆ 14098.627 ┆ null      ┆ 289.0     │
│ 50%       ┆ null      ┆ null      ┆ null     ┆ … ┆ 3.0       ┆ 18067.925 ┆ null      ┆ 459.0     │
│ 75%       ┆ null      ┆ null      ┆ null     ┆ … ┆ 4.0       ┆ 19189.779 ┆ null      ┆ 628.0     │
│ max       ┆ ff79f1669 ┆ 352020498 ┆ FINISHED ┆ … ┆ 5.0       ┆ 29403.837 ┆ 8h 10m    ┆ 797.0     │
│           ┆ eac406f8f ┆ 793752715 ┆          ┆   ┆           ┆           ┆ 03s       ┆           │
│           ┆ e93c31e7e ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 7f3…      ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [89]:
remove_df.describe()

shape: (9, 176)
┌────────────┬───────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ run_id    ┆ experimen ┆ status  ┆ … ┆ data.mask ┆ duration_ ┆ duration_ ┆ __index_l │
│ ---        ┆ ---       ┆ t_id      ┆ ---     ┆   ┆ .model_in ┆ seconds   ┆ formatted ┆ evel_0__  │
│ str        ┆ str       ┆ ---       ┆ str     ┆   ┆ dex       ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆ str       ┆         ┆   ┆ ---       ┆ f64       ┆ str       ┆ f64       │
│            ┆           ┆           ┆         ┆   ┆ f64       ┆           ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 120       ┆ 120       ┆ 120     ┆ … ┆ 120.0     ┆ 120.0     ┆ 120       ┆ 120.0     │
│ null_count ┆ 0         ┆ 0         ┆ 0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0.0       │
│ mean       ┆ null      ┆ null      ┆ null    ┆ … ┆ 2.5       ┆ 4148.0487 ┆ null      ┆ 60.291667 │
│            ┆           ┆           ┆         ┆   ┆           ┆ 54        ┆           ┆           │
│ std        ┆ null      ┆ null      ┆ null    ┆ … ┆ 1.714986  ┆ 3382.6526 ┆ null      ┆ 36.634556 │
│            ┆           ┆           ┆         ┆   ┆           ┆ 55        ┆           ┆           │
│ min        ┆ 02ca563bd ┆ 352020498 ┆ RUNNING ┆ … ┆ 0.0       ┆ 1541.8378 ┆ 1h 00m    ┆ 0.0       │
│            ┆ a9f49adb1 ┆ 793752715 ┆         ┆   ┆           ┆ 54        ┆ 20s       ┆           │
│            ┆ d5fa30df0 ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│            ┆ 562…      ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ null      ┆ null      ┆ null    ┆ … ┆ 1.0       ┆ 3144.3218 ┆ null      ┆ 30.0      │
│            ┆           ┆           ┆         ┆   ┆           ┆ 54        ┆           ┆           │
│ 50%        ┆ null      ┆ null      ┆ null    ┆ … ┆ 3.0       ┆ 3737.2948 ┆ null      ┆ 60.0      │
│            ┆           ┆           ┆         ┆   ┆           ┆ 54        ┆           ┆           │
│ 75%        ┆ null      ┆ null      ┆ null    ┆ … ┆ 4.0       ┆ 4385.2578 ┆ null      ┆ 89.0      │
│            ┆           ┆           ┆         ┆   ┆           ┆ 54        ┆           ┆           │
│ max        ┆ ffdd11bc2 ┆ 352020498 ┆ RUNNING ┆ … ┆ 5.0       ┆ 28961.067 ┆ 8h 02m    ┆ 172.0     │
│            ┆ f6a4b5585 ┆ 793752715 ┆         ┆   ┆           ┆ 854       ┆ 41s       ┆           │
│            ┆ 481a29c8d ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│            ┆ f59…      ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [94]:
keep_path = FILE_PATH.with_name(FILE_PATH.name.replace("_runs", "_runs_keep"))
keep_df.write_parquet(keep_path)
files = [
    i for i in COMMANDS_FOLDER.iterdir()
    if i.suffix == ".txt" and i.stem[:-2] in str(FILE_PATH.stem).replace("-", "_")
]
files

[PosixPath('/Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_5.txt'),
 PosixPath('/Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_4.txt'),
 PosixPath('/Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_0.txt'),
 PosixPath('/Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_1.txt'),
 PosixPath('/Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_3.txt'),
 PosixPath('/Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_2.txt')]

In [95]:
script_path = SCRIPTS_PATH / "filter_commands.py"
for f in files:
    !uv run python "{script_path}" "{f}" -r "{keep_path}"

INFO: Loading runs from parquet file: /Users/ronholzapfel/Documents/private/privacy-and-grokking/cache/hyper-sweep-v1_runs_keep.parquet
INFO: Filtered runs in parquet by status ['FINISHED']: 678 / 678 matching runs.
INFO: Processed 565 lines: 80 commands filtered out (already run), 485 remaining to run.
INFO: Wrote remaining commands to: /Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_5.txt
INFO: Loading runs from parquet file: /Users/ronholzapfel/Documents/private/privacy-and-grokking/cache/hyper-sweep-v1_runs_keep.parquet
INFO: Filtered runs in parquet by status ['FINISHED']: 678 / 678 matching runs.
INFO: Processed 565 lines: 80 commands filtered out (already run), 485 remaining to run.
INFO: Wrote remaining commands to: /Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_4.txt
INFO: Loading runs from parquet file: /Users/ronholzapfel/Documents/private/privacy-and-grokking/cache/hyper-sweep-v1_runs_keep.parquet
INFO: Filtered runs in parquet by status ['FINISHED']: 678 / 678 matching runs.
INFO: Processed 565 lines: 40 commands filtered out (already run), 525 remaining to run.
INFO: Wrote remaining commands to: /Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_0.txt
INFO: Loading runs from parquet file: /Users/ronholzapfel/Documents/private/privacy-and-grokking/cache/hyper-sweep-v1_runs_keep.parquet
INFO: Filtered runs in parquet by status ['FINISHED']: 678 / 678 matching runs.
INFO: Processed 565 lines: 40 commands filtered out (already run), 525 remaining to run.
INFO: Wrote remaining commands to: /Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_1.txt
INFO: Loading runs from parquet file: /Users/ronholzapfel/Documents/private/privacy-and-grokking/cache/hyper-sweep-v1_runs_keep.parquet
INFO: Filtered runs in parquet by status ['FINISHED']: 678 / 678 matching runs.
INFO: Processed 565 lines: 39 commands filtered out (already run), 526 remaining to run.
INFO: Wrote remaining commands to: /Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_3.txt
INFO: Loading runs from parquet file: /Users/ronholzapfel/Documents/private/privacy-and-grokking/cache/hyper-sweep-v1_runs_keep.parquet
INFO: Filtered runs in parquet by status ['FINISHED']: 678 / 678 matching runs.
INFO: Processed 565 lines: 39 commands filtered out (already run), 526 remaining to run.
INFO: Wrote remaining commands to: /Users/ronholzapfel/Documents/private/privacy-and-grokking/commands/hyper_sweep_2.txt

In [97]:
for id in remove_df["run_id"]:
    print(f"Removing {id}")
    client.delete_run(id)

Removing 6350b4aa7ca143aab934022d9f9ebec2
Removing f84b3d198c2545af9c36af4dc3c9066a
Removing 1b66dd35a8b244ca96edc8c892c0b8f0
Removing c91b213f865f4d1d9c6ca79c8f1b7abe
Removing f9b357e2e0974de9b6702f428c8bd41c
Removing 93402ebc191f4a718c15d366ffd5d093
Removing 48d7f7533b44449b9deb235d46206cfd
Removing 3d673f7f90f04e71ad422275a6c86926
Removing c245b5080c2040bcada974c74fd0aef8
Removing 045fcba1615e482ca981ad820f5e7aba
Removing 72cb51a3a9964435bde888f72c717144
Removing 2e0e99d514f1429cbe9835ad0ddc39a9
Removing f89efdaf77cf4a1f8d990020e205f35c
Removing a59d7f3454034172a5b73da23d272bb2
Removing b931f94369a6469ba54c52e13aa792b7
Removing e52154bcbe124b4b9e49691c2cad6f31
Removing cc0ecfef3ccb449f8b28d4ec0d40eeaf
Removing e25b10455e2a4d4d8dea40305792d288
Removing bdf2a29d46cf44778f32d8c25eb45ef6
Removing 8acde2371c684782ad9c176ba269eb6a
Removing 999ed1151b6a4773a5327ef1011c0ecb
Removing f4c6996ee3444ec4bba8a00ce9396ade
Removing 2c8648effdc640149f5589d9ea27075b
Removing 228eaab06af84f16bb4415f8fbce5baf
Removing 2a3d212ae50b4c6692304b56fd185d15
Removing 947cf3c6b9b64c63aaa05e14dfaffc23
Removing 638e492008184a14a39b8d56cfddac07
Removing e2a9160b952d448da5a7ef5949089db1
Removing 292e4722d600442698d627c59b77f3ae
Removing 4a871742ffa2455282fce9774e33207d
Removing 9c4b5e7dc13d491eba9f080183e77fce
Removing 4da25846fe2d4a64a39d58ed647fd238
Removing 8adb8c7a96934c3890bda3eaf138fe68
Removing ac6ce655c98b4fdcbe7b1a6a63f0c8f7
Removing f8e713f3d7d64f9db7e9672db07b1632
Removing 4fbca95346d64153bad586132f53a1c8
Removing 89b69ee0795a4be7835c7e8a49c1df10
Removing ad59074c6abb4e13af6285efac1560e7
Removing 70ca6540719e41e1af340d42d7fda72c
Removing 5178db6e07b54d8f9087a0a63e14bbec
Removing 9a7d1871a0b042d3a37a6b9fa25055a6
Removing 26db58063075448c9c51518db0cc877b
Removing fcd4ed6970d94dbab8136f216a194fe2
Removing a90e217b47b64ce8ba398cea2664d183
Removing af339b56d7d84e978800640a0b76f449
Removing a6ea4df28e134f93bb7362183ce2162a
Removing b1b9a8476e8c4d48a1b72b1051ac6c9b
Removing 4ed037245046479ba70f691c9c1b6199
Removing 86af59e9d52445caa210282658ac9d0e
Removing 27db98092bb645969cc2699551ef7a70
Removing 29135077a160443ca02b476bd26c39f5
Removing 927e23eb033e48849438988594f2ac5f
Removing 22b68ba59e114755a19f89157e43ee46
Removing 267f854d55ff405c8cb8262718049bc6
Removing 8758f1d411bf415cb76dc0f2897c6d2f
Removing fbe40a9ab32342ab82cf2a16688311ff
Removing 03b253ea86d04801bf9632c40ed32186
Removing c8e5dafda20844508407b4eaf059270c
Removing 950323eb45cc4e19b2d3f6566b23c297
Removing cdaee6bfcacb4dadae739ff1993691dd
Removing 9367272cb92d4fc4a611991473fb15cd
Removing fae08315bb02443f9a02ae5ad8729844
Removing e22861da4e354aef979b6f424742bd09
Removing 6217ddf279f34444b9bdcdee61546403
Removing 556a3115a2b94406b559a8ed9d0f557b
Removing 704db940dd2944dcb7c91c50ed5e21c2
Removing 4ba544bc07424fe899c2cae618d693cf
Removing f1489daa4c624951a2b84cfedbecfd99
Removing b4f8ee7a7e144b6fb6a743cdaab38971
Removing e46b26839a9548e7a2fb2b52a2993b4d
Removing 426c0228ede740758ea043f6964d0ce0
Removing 9d36bb06e7a04137844362307feaf941
Removing a544821c91b548f2addd00219906b2f1
Removing b3226dc8c1624350afd70a47a0fcbd7a
Removing 18777d36e38d46b4a04e929452b1e3b1
Removing ffdd11bc2f6a4b5585481a29c8df5918
Removing 9c01a6181fd447e1982fc58ce85339c3
Removing d325fa283a6046819eb193bd49494b16
Removing 8db2189d8e884b4780ed84bbe97f565b
Removing 033e3e984c4748ce82b42098a50bc3ed
Removing 98a72eb839e3439e829715685ec3abae
Removing 9549ff740a64474bb0af1fb84ab27858
Removing 49afb6ce95714e909dd59f9213d0c88a
Removing bffd76ad4cd840f2835000dffabf6e1c
Removing bd10a67f7d3b46a58d6bcb52c26b278a
Removing ccf28adecead4a5db53098df36a8e1ba
Removing 719e991a95c24408a661b601eb714d42
Removing 67790b1c389b471f89ee432c3a246fe3
Removing 90de821230df4787a57bb91999139524
Removing a366ac4d9e3a4be09a3151635fa5d08d
Removing b131f4e3cbd644f4b498698e2c66c4e6
Removing 491edcaee09545dba45af40cf737e1da
Removing 551afca4ce4a4d8788f3007929516f98
Removing a97ae30d68424599b916820e6334cf6d
Removing 1936272ff8d74e8dba45f21cd2d817ab
Removing f6f2cb005b894010a17798014dc6fac4
Removing ca20f553a22945f18a91c21468bc7d93
Removing 6361c37657864af38217b7fca7011075
Removing 20ed65f8f42c45a0af0196c8b439dbf0
Removing 0e05ef4cf67b4485a490913a0d02bba5
Removing 8d0cb6c6e5f74680a86b651a29cff933
Removing 45c8b08b80e04c3fa1517cb0ab7e4b22
Removing 3d467274466e4074b3e18ced6e6ed51a
Removing f03494f738b9422cb4f0c97ddaa68a48
Removing 67d805094ed44fbc8e77af1fc876d25c
Removing 83cd2fb25eff4cae8d823d03ec7a6877
Removing 20c7679b242947798f25f2e6e77d656f
Removing c90142f5fdfa4ebf93317ff7881ad9af
Removing bede9bd144d34271b73843c8edd5b54b
Removing 4ddfc2f2a6ff40aa8ec32b20604dbcf3
Removing 25908104bf1d48dcb0380336b138fdd2
Removing eda9b96b80744c32ade836554c8a31f6
Removing 44bc1e523adc48daafc24507e8e2b630
Removing b6c86b4fb3154814be6ca8e759d58e2d
Removing 02ca563bda9f49adb1d5fa30df0562c8
Removing 1602125db88f4b71a9320bc74dfc92e1
Removing cc2bf1d6ae5b4456ad0aa630c3dd214c
Removing 2eb98b6c55a14c8a883c302f4463245e
Removing 2ca39125da3a4c0693e3340520adeeac
Removing ced7eeb1ac6f4e079b8a8975a4c3519e

In [96]:
keep_df

shape: (678, 175)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ run_id    ┆ experimen ┆ status   ┆ artifact_ ┆ … ┆ data.mask ┆ duration_ ┆ duration_ ┆ __index_l │
│ ---       ┆ t_id      ┆ ---      ┆ uri       ┆   ┆ .model_in ┆ seconds   ┆ formatted ┆ evel_0__  │
│ str       ┆ ---       ┆ str      ┆ ---       ┆   ┆ dex       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆          ┆ str       ┆   ┆ ---       ┆ f64       ┆ str       ┆ i64       │
│           ┆           ┆          ┆           ┆   ┆ i64       ┆           ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ f1946068d ┆ 352020498 ┆ FINISHED ┆ file:///w ┆ … ┆ 4         ┆ 12929.938 ┆ 3h 35m    ┆ 118       │
│ bba4c39ac ┆ 793752715 ┆          ┆ orkspace/ ┆   ┆           ┆           ┆ 29s       ┆           │
│ 73066e2d2 ┆           ┆          ┆ mlruns/hy ┆   ┆           ┆           ┆           ┆           │
│ 8fd…      ┆           ┆          ┆ per…      ┆   ┆           ┆           ┆           ┆           │
│ ca4117e73 ┆ 352020498 ┆ FINISHED ┆ file:///w ┆ … ┆ 5         ┆ 12924.861 ┆ 3h 35m    ┆ 119       │
│ b994639b3 ┆ 793752715 ┆          ┆ orkspace/ ┆   ┆           ┆           ┆ 24s       ┆           │
│ 33d54ed18 ┆           ┆          ┆ mlruns/hy ┆   ┆           ┆           ┆           ┆           │
│ c83…      ┆           ┆          ┆ per…      ┆   ┆           ┆           ┆           ┆           │
│ 5d0c7a187 ┆ 352020498 ┆ FINISHED ┆ file:///w ┆ … ┆ 4         ┆ 13434.19  ┆ 3h 43m    ┆ 120       │
│ 82f494f9b ┆ 793752715 ┆          ┆ orkspace/ ┆   ┆           ┆           ┆ 54s       ┆           │
│ 9757c4707 ┆           ┆          ┆ mlruns/hy ┆   ┆           ┆           ┆           ┆           │
│ e68…      ┆           ┆          ┆ per…      ┆   ┆           ┆           ┆           ┆           │
│ 2e81b81b3 ┆ 352020498 ┆ FINISHED ┆ file:///w ┆ … ┆ 5         ┆ 13445.442 ┆ 3h 44m    ┆ 121       │
│ b3a4e3c99 ┆ 793752715 ┆          ┆ orkspace/ ┆   ┆           ┆           ┆ 05s       ┆           │
│ c0697a8c0 ┆           ┆          ┆ mlruns/hy ┆   ┆           ┆           ┆           ┆           │
│ 6e8…      ┆           ┆          ┆ per…      ┆   ┆           ┆           ┆           ┆           │
│ f61e59950 ┆ 352020498 ┆ FINISHED ┆ file:///w ┆ … ┆ 5         ┆ 13064.83  ┆ 3h 37m    ┆ 122       │
│ 0a745938e ┆ 793752715 ┆          ┆ orkspace/ ┆   ┆           ┆           ┆ 44s       ┆           │
│ 4b67d9877 ┆           ┆          ┆ mlruns/hy ┆   ┆           ┆           ┆           ┆           │
│ 31a…      ┆           ┆          ┆ per…      ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 9902eca92 ┆ 352020498 ┆ FINISHED ┆ file:///w ┆ … ┆ 5         ┆ 18094.506 ┆ 5h 01m    ┆ 793       │
│ fe94a3fbf ┆ 793752715 ┆          ┆ orkspace/ ┆   ┆           ┆           ┆ 34s       ┆           │
│ 3acc59d55 ┆           ┆          ┆ mlruns/hy ┆   ┆           ┆           ┆           ┆           │
│ 3ca…      ┆           ┆          ┆ per…      ┆   ┆           ┆           ┆           ┆           │
│ c8f31e291 ┆ 352020498 ┆ FINISHED ┆ file:///w ┆ … ┆ 5         ┆ 17961.464 ┆ 4h 59m    ┆ 794       │
│ cd94acb81 ┆ 793752715 ┆          ┆ orkspace/ ┆   ┆           ┆           ┆ 21s       ┆           │
│ c7f5c7e4d ┆           ┆          ┆ mlruns/hy ┆   ┆           ┆           ┆           ┆           │
│ 5cd…      ┆           ┆          ┆ per…      ┆   ┆           ┆           ┆           ┆           │
│ e574b9fb5 ┆ 352020498 ┆ FINISHED ┆ file:///w ┆ … ┆ 5         ┆ 18018.409 ┆ 5h 00m    ┆ 795       │
│ 0ce4dc689 ┆ 793752715 ┆          ┆ orkspace/ ┆   ┆           ┆           ┆ 18s       ┆           │
│ aadf43291 ┆           ┆          ┆ mlruns/hy ┆   ┆           ┆           ┆           ┆           │
│ 168…      ┆           ┆          ┆ per…      ┆   ┆           ┆           ┆           ┆           │
│ ff540c289 ┆ 352020498 ┆ FINISHED ┆ file:///w ┆ … ┆ 5         ┆ 18790.319 ┆ 5h 13m    ┆ 796       │
│ 6c2484fad ┆ 793752715 ┆          ┆ orkspace/ ┆   ┆           ┆           ┆ 10s       ┆           │
│ 2976513c2 ┆           ┆          ┆ mlruns/hy ┆   ┆           ┆           ┆           ┆           │
│ 37b…      ┆           ┆          ┆ per…      ┆   ┆           ┆           ┆           ┆           │
│ 3db1c1854 ┆ 352020498 ┆ FINISHED ┆ file:///w ┆ … ┆ 5         ┆ 17951.345 ┆ 4h 59m    ┆ 797       │
│ 3a34b08ae ┆ 793752715 ┆          ┆ orkspace/ ┆   ┆           ┆           ┆ 11s       ┆           │
│ dc4408cc6 ┆           ┆          ┆ mlruns/hy ┆   ┆           ┆           ┆           ┆           │
│ 5cd…      ┆           ┆          ┆ per…      ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘